version: '3.5'
services:

  builder:
    build:
      context: ./
      target: logger_builder
    container_name: logger_builder
    volumes:
      - ./backend:/usr/src/app
    networks:
      - network
    command: sh -c "npm run dev"

  backend:
    build: 
      context: ./
      target: logger_backend
    container_name: logger
    depends_on:
      - builder
    volumes:
      - ./backend:/usr/src/app
    networks:
      - network
    ports:
      - "4554:4554"

networks:
  network: